DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
	id SERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL,
	accepted_at TIMESTAMP,
	completed_at TIMESTAMP,
  total BIGINT,
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
  );
